/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dwpuntoventa.gui.main;

import dwpuntoventa.gui.MAyuda.VAcercaDe;

/**
 *
 * @author daniel
 */
public class VMain extends javax.swing.JFrame {

    
    private VAcercaDe vacercade = null;
    /**
     * Creates new form VMain
     */
    public VMain() {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDesk = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlTabArticulos = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pnlTabProveedores = new javax.swing.JPanel();
        pnlTabInventario = new javax.swing.JPanel();
        pnlTabReportes = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuApp = new javax.swing.JMenu();
        menuArticulos = new javax.swing.JMenu();
        actCatArt = new javax.swing.JMenuItem();
        actNvoArt = new javax.swing.JMenuItem();
        actModifArt = new javax.swing.JMenuItem();
        menuProveedores = new javax.swing.JMenu();
        actCatProv = new javax.swing.JMenuItem();
        actNvoProv = new javax.swing.JMenuItem();
        actModifProv = new javax.swing.JMenuItem();
        menuInventario = new javax.swing.JMenu();
        actMovArt = new javax.swing.JMenuItem();
        actAjusteProd = new javax.swing.JMenuItem();
        actExistenciaDia = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        actRepExistencias = new javax.swing.JMenuItem();
        actRepEntradas = new javax.swing.JMenuItem();
        actRepSalidas = new javax.swing.JMenuItem();
        actRepAjustes = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        actAdminUser = new javax.swing.JMenuItem();
        actCatUsuarios = new javax.swing.JMenuItem();
        menuConfig = new javax.swing.JMenu();
        actTienda = new javax.swing.JMenuItem();
        actConexRem = new javax.swing.JMenuItem();
        actRespaldo = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        actAcercaDe = new javax.swing.JMenuItem();
        actLog = new javax.swing.JMenuItem();
        actDatosTienda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1393, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlTabArticulos.setViewportView(jPanel1);

        jTabbedPane1.addTab("Articulos", pnlTabArticulos);

        javax.swing.GroupLayout pnlTabProveedoresLayout = new javax.swing.GroupLayout(pnlTabProveedores);
        pnlTabProveedores.setLayout(pnlTabProveedoresLayout);
        pnlTabProveedoresLayout.setHorizontalGroup(
            pnlTabProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1412, Short.MAX_VALUE)
        );
        pnlTabProveedoresLayout.setVerticalGroup(
            pnlTabProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Proveedores", pnlTabProveedores);

        javax.swing.GroupLayout pnlTabInventarioLayout = new javax.swing.GroupLayout(pnlTabInventario);
        pnlTabInventario.setLayout(pnlTabInventarioLayout);
        pnlTabInventarioLayout.setHorizontalGroup(
            pnlTabInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1412, Short.MAX_VALUE)
        );
        pnlTabInventarioLayout.setVerticalGroup(
            pnlTabInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Inventario", pnlTabInventario);

        javax.swing.GroupLayout pnlTabReportesLayout = new javax.swing.GroupLayout(pnlTabReportes);
        pnlTabReportes.setLayout(pnlTabReportesLayout);
        pnlTabReportesLayout.setHorizontalGroup(
            pnlTabReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1412, Short.MAX_VALUE)
        );
        pnlTabReportesLayout.setVerticalGroup(
            pnlTabReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reportes", pnlTabReportes);

        menuApp.setText("Aplicacion");
        menuBar.add(menuApp);

        menuArticulos.setText("Articulos");

        actCatArt.setText("Catalogo");
        menuArticulos.add(actCatArt);

        actNvoArt.setText("Nuevo");
        actNvoArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actNvoArtActionPerformed(evt);
            }
        });
        menuArticulos.add(actNvoArt);

        actModifArt.setText("Modificar");
        menuArticulos.add(actModifArt);

        menuBar.add(menuArticulos);

        menuProveedores.setText("Proveedores");

        actCatProv.setText("Catalogo");
        menuProveedores.add(actCatProv);

        actNvoProv.setText("Nuevo");
        menuProveedores.add(actNvoProv);

        actModifProv.setText("Modificar");
        menuProveedores.add(actModifProv);

        menuBar.add(menuProveedores);

        menuInventario.setText("Inventario");

        actMovArt.setText("Entradas y Salidas");
        menuInventario.add(actMovArt);

        actAjusteProd.setText("Ajustes de Existencias");
        menuInventario.add(actAjusteProd);

        actExistenciaDia.setText("Existencia del Dia");
        menuInventario.add(actExistenciaDia);

        menuBar.add(menuInventario);

        menuReportes.setText("Reportes");

        actRepExistencias.setText("Existencias");
        menuReportes.add(actRepExistencias);

        actRepEntradas.setText("Entradas");
        actRepEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actRepEntradasActionPerformed(evt);
            }
        });
        menuReportes.add(actRepEntradas);

        actRepSalidas.setText("Salidas");
        menuReportes.add(actRepSalidas);

        actRepAjustes.setText("Ajustes");
        menuReportes.add(actRepAjustes);

        menuBar.add(menuReportes);

        menuUsuarios.setText("Usuarios");

        actAdminUser.setText("Administracion");
        menuUsuarios.add(actAdminUser);

        actCatUsuarios.setText("Catalogo");
        menuUsuarios.add(actCatUsuarios);

        menuBar.add(menuUsuarios);

        menuConfig.setText("Configuracion");

        actTienda.setText("Tienda");
        menuConfig.add(actTienda);

        actConexRem.setText("Conexion Remota");
        menuConfig.add(actConexRem);

        actRespaldo.setText("Repaldo");
        menuConfig.add(actRespaldo);

        menuBar.add(menuConfig);

        menuAyuda.setText("Ayuda");

        actAcercaDe.setText("Acerca de");
        actAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(actAcercaDe);

        actLog.setText("Log Aplicacion");
        menuAyuda.add(actLog);

        actDatosTienda.setText("Datos de Tienda");
        menuAyuda.add(actDatosTienda);

        menuBar.add(menuAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDesk)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDesk, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actRepEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actRepEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actRepEntradasActionPerformed

    private void actNvoArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actNvoArtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actNvoArtActionPerformed

    /**
     * MEtodo para mostrar la pantalla del acerca de
     * @param evt 
     */
    private void actAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actAcercaDeActionPerformed
        try{
            if(vacercade == null){
                vacercade = new VAcercaDe();
                
                this.vacercade.setVisible(true);
                this.vacercade.setSize(this.vacercade.getPreferredSize().width,this.vacercade.getPreferredSize().height);
                this.vacercade.setLocation(this.centrarVentana(this.vacercade.getSize()));
                
                this.panelDesk.add(vacercade);
                try{
                    this.vacercade.setSelected(true);
                }catch(Exception ex){
                    
                }
                this.panelDesk.setSelectedFrame(this.vacercade);
            }else{
                this.vacercade.setVisible(true);
                this.vacercade.setSize(this.vacercade.getPreferredSize().width,this.vacercade.getPreferredSize().height);
                this.vacercade.setLocation(this.centrarVentana(this.vacercade.getSize()));
                try{
                    this.vacercade.setSelected(true);
                }catch(Exception ex){
                    
                }
                this.panelDesk.setSelectedFrame(this.vacercade);
            }
            
            this.vacercade = null;
        }catch(Exception ex){
            System.out.println("EX: actAcercaDeActionPerformed " + ex);
        }
    }//GEN-LAST:event_actAcercaDeActionPerformed

    
    /**
     * Metodo para poner la ventana al centro del JDesktop principal
     * @param jfDim
     * @return 
     */
    private java.awt.Point centrarVentana(java.awt.Dimension jfDim){
        java.awt.Dimension jInternalFrameSize = jfDim;
        java.awt.Dimension desktopSize = this.panelDesk.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        
        return new java.awt.Point(width, height);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actAcercaDe;
    private javax.swing.JMenuItem actAdminUser;
    private javax.swing.JMenuItem actAjusteProd;
    private javax.swing.JMenuItem actCatArt;
    private javax.swing.JMenuItem actCatProv;
    private javax.swing.JMenuItem actCatUsuarios;
    private javax.swing.JMenuItem actConexRem;
    private javax.swing.JMenuItem actDatosTienda;
    private javax.swing.JMenuItem actExistenciaDia;
    private javax.swing.JMenuItem actLog;
    private javax.swing.JMenuItem actModifArt;
    private javax.swing.JMenuItem actModifProv;
    private javax.swing.JMenuItem actMovArt;
    private javax.swing.JMenuItem actNvoArt;
    private javax.swing.JMenuItem actNvoProv;
    private javax.swing.JMenuItem actRepAjustes;
    private javax.swing.JMenuItem actRepEntradas;
    private javax.swing.JMenuItem actRepExistencias;
    private javax.swing.JMenuItem actRepSalidas;
    private javax.swing.JMenuItem actRespaldo;
    private javax.swing.JMenuItem actTienda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu menuApp;
    private javax.swing.JMenu menuArticulos;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConfig;
    private javax.swing.JMenu menuInventario;
    private javax.swing.JMenu menuProveedores;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JDesktopPane panelDesk;
    private javax.swing.JScrollPane pnlTabArticulos;
    private javax.swing.JPanel pnlTabInventario;
    private javax.swing.JPanel pnlTabProveedores;
    private javax.swing.JPanel pnlTabReportes;
    // End of variables declaration//GEN-END:variables
}
